# YAML copied from: https://realpython.com/python-logging/#other-configuration-methods
version: 1
disable_existing_loggers: false

formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detailed
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/seleniumtabs.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/seleniumtabs_error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

root:
  level: DEBUG
  handlers: [console, file, error_file]
  propagate: true
